---
title: "3_tanner_and_ema_and_act"
author: "Jackie"
date: "03/16/22"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

# loading libraries
```{r, message=FALSE}
library(lmerTest)
library(tidyverse)
library(foreign)
library(haven)
library(readxl)
library(naniar)
library(lubridate)
```

# Reading in data from 2_demo_cleaning

```{r}
dem_plus_tan_t1_fp <- "~/Dropbox/JSK_SC/_scripts/1_demo_wrangling/dem_plus_tan_t1.csv"
dem_plus_tan_t1 <- 
  read_csv(dem_plus_tan_t1_fp) %>%
  mutate(
    ELS_ID = factor(ELS_ID)
  )

dem_plus_tan_t3_fp <- "~/Dropbox/JSK_SC/_scripts/1_demo_wrangling/dem_plus_tan_t3_act_ema.csv"
dem_plus_tan_t3 <- 
  read_csv(dem_plus_tan_t3_fp) %>%
  mutate(
    ELS_ID = factor(ELS_ID)
  ) %>%
  dplyr::select(ELS_ID, sex, simiul_ahc_t3, interval_mw_and_act_t3, tanner_date.T3, interval_btwn_ema_and_tanner, interval_btwn_act_and_tanner, Age.T3, BMI.T3, tanner_average.T3, Contraceptive.T3:Household_Income.T3) %>%
  mutate(
    timept_t3 = "T3"
  )

dem_plus_tan_t4_fp <- "~/Dropbox/JSK_SC/_scripts/1_demo_wrangling/dem_plus_tan_t4_act_ema.csv"
dem_plus_tan_t4 <- 
  read_csv(dem_plus_tan_t4_fp) %>%
  mutate(
    ELS_ID = factor(ELS_ID)
  ) %>%
  dplyr::select(ELS_ID, sex, simul_ahc_t4, interval_mw_and_act_t4, tanner_date.T4, interval_btwn_ema_and_tanner, interval_btwn_act_and_tanner, Age.T4, BMI.T4, tanner_average.T4, Sexual_Orientation.T4, Gender.T4, Gender_other.T4, Primary_Parent_Education.T4:Household_Income.T4) %>%
  mutate(
    timept_t4 = "T4"
  )
```

## Combining data

```{r}
dem_plus_tan_t3_clean <-
  dem_plus_tan_t3 %>%
  dplyr::rename(
    simul_ahc = simiul_ahc_t3,
    interval_ema_and_act = interval_mw_and_act_t3,
    tanner_date_ahc = tanner_date.T3,
    Age_ahc = Age.T3,
    BMI_ahc = BMI.T3,
    tanner_average_ahc = tanner_average.T3,
    Contraceptive_use = Contraceptive.T3,
    Allergy_Antibiotic_use = Allergy_Antibiotic.T3,
    Corticosteroid_Use = Corticosteroid_Use.T3,
    Illness = Illness.T3,
    Dx_Group_ahc = Dx_Group.T3,
    Psych_Med_ahc = Psych_Med.T3,
    Household_Income_ahc = Household_Income.T3,
    timept = timept_t3
    ) %>%
  dplyr::select(-c(Contraceptive_use:Psych_Med_ahc))

dem_plus_tan_t4_clean <-
  dem_plus_tan_t4 %>%
  dplyr::rename(
    simul_ahc = simul_ahc_t4,
    interval_ema_and_act = interval_mw_and_act_t4,
    tanner_date_ahc = tanner_date.T4,
    Age_ahc = Age.T4,
    BMI_ahc = BMI.T4,
    tanner_average_ahc = tanner_average.T4,
    Household_Income_ahc = Household_Income.T4,
    timept = timept_t4
    ) %>%
  dplyr::select(-c(Sexual_Orientation.T4:Home_Ownership_Status.T4))

dem_plus_tan_ahc_merge <-
  rbind(dem_plus_tan_t3_clean, dem_plus_tan_t4_clean) %>% 
  mutate(ELS_ID = factor(ELS_ID))


dem_plus_tan_ahc_merge <-
  left_join(
    dem_plus_tan_ahc_merge,
    dem_plus_tan_t1,
    by = "ELS_ID"
  ) %>%
  relocate(Child_Sex.T1, .after = sex) %>%
  mutate(match_sex = Child_Sex.T1 == sex) %>%
  relocate(match_sex, .after = Child_Sex.T1) %>%
  relocate(timept, .after = Child_Sex.T1) %>%
  mutate(ELS_ID = factor(ELS_ID))
  
```

# Reading in cmep data

```{r, message=FALSE}

varscmept3 <- c("cmep_1.T3", "cmep_2.T3", "cmep_3.T3", "cmep_4.T3", "cmep_5.T3", "cmep_6.T3", "cmep_7.T3", "cmep_8.T3", "cmep_9.T3", "cmep_10.T3")

cmept3_fp <- "~/Dropbox/JSK_SC/els_measures/cmep/cmep.T3.csv"
cmept3 <- 
  read_csv(cmept3_fp) %>%
  replace_with_na_at(., .vars = varscmept3, condition = ~.x == 888) %>%
  dplyr::mutate(
    ELS_ID = factor(ELS_ID)
  ) %>%
  filter(
    !Subject_ID_Timepoint == "196-T3"
  ) %>%
  dplyr::mutate(
    ELS_ID = substr(Subject_ID_Timepoint,1,3),
    ELS_ID = as.numeric(ELS_ID),
    ELS_ID = factor(ELS_ID)
  )
cmept3_clean <-
  cmept3 %>%
  mutate(
    cmep_total.T3 = rowSums(cmept3[,(varscmept3)])
  )


varscmept4 <- c("cmep_1.T4", "cmep_2.T4", "cmep_3.T4", "cmep_4.T4", "cmep_5.T4", "cmep_6.T4", "cmep_7.T4", "cmep_8.T4", "cmep_9.T4", "cmep_10.T4")

cmept4_fp <- "~/Dropbox/JSK_SC/els_measures/cmep/cmep.T4.csv"
cmept4 <- 
  read_csv(cmept4_fp) %>%
  replace_with_na_at(., .vars = varscmept4, condition = ~.x == 888) %>%
  dplyr::mutate(
    ELS_ID = substr(Subject_ID_Timepoint,1,3),
    ELS_ID = as.numeric(ELS_ID),
    ELS_ID = factor(ELS_ID)
  ) 

cmept4_clean <-
  cmept4 %>%
  dplyr::mutate(
    cmep_total.T4 = rowSums(cmept4[,(varscmept4)])
  )

```

## Merging cmep with rest of data

```{r}
cmept3_clean <-
  cmept3_clean %>%
  mutate(
    dup = duplicated(ELS_ID)
  ) %>%
  dplyr::select(ELS_ID, cmep_date.T3, cmep_total.T3) %>%
  drop_na(cmep_total.T3)

cmept4_clean <-
  cmept4_clean %>%
  mutate(
    dup = duplicated(ELS_ID)
  ) %>%
  dplyr::select(ELS_ID, cmep_date.T4, cmep_total.T4) %>%
  drop_na(cmep_total.T4)
  
  
dem_plus_tan_ahc_merge2 <-
  left_join(
    dem_plus_tan_ahc_merge,
    cmept3_clean,
    by = "ELS_ID"
  ) %>%
  select(-match_sex, -sex) %>%
  dplyr::rename(sex = Child_Sex.T1)

dem_plus_tan_ahc_merge3 <-
  left_join(
    dem_plus_tan_ahc_merge2,
    cmept4_clean,
    by = "ELS_ID"
  ) %>%
  dplyr::mutate(
    cmep_total = ifelse(ELS_ID == "6" | ELS_ID == "17" | ELS_ID == "38" | ELS_ID == "101" | ELS_ID == "192", cmep_total.T4, cmep_total.T3)
  ) %>%
  mutate(ELS_ID = factor(ELS_ID))
```


### Merging ASQ with rest of data

```{r}
asqt3_fp <- "~/Dropbox/JSK_SC/els_measures/asq/asq_score_t3.csv"
asqt3 <- 
  read_csv(asqt3_fp) %>%
  mutate(
    ELS_ID = as.numeric(ELS_ID),
    ELS_ID = as.character(ELS_ID)
  ) %>%
  mutate(
    ELS_ID = as.factor(ELS_ID)
  )

asqt4_fp <- "~/Dropbox/JSK_SC/els_measures/asq/asq_score_t4.csv"
asqt4 <- 
  read_csv(asqt4_fp) %>%
  mutate(
    ELS_ID = as.numeric(ELS_ID),
    ELS_ID = as.character(ELS_ID)
  ) %>%
  mutate(
    ELS_ID = as.factor(ELS_ID)
  )

dem_plus_tan_ahc_merge4 <-
  left_join(
    dem_plus_tan_ahc_merge3,
    asqt3,
    by = "ELS_ID"
  )

dem_plus_tan_ahc_merge5 <-
  left_join(
    dem_plus_tan_ahc_merge4,
    asqt4,
    by = "ELS_ID"
  ) %>%
  dplyr::mutate(
    ASQ_total = ifelse(ELS_ID == "6" | ELS_ID == "17" | ELS_ID == "38" | ELS_ID == "101" | ELS_ID == "192", ASQ_total.T4, ASQ_total.T3)
  )
```


### getting rid of redundant ids

```{r}

dem_plus_tan_ahc_merge6 <-
  dem_plus_tan_ahc_merge5 %>%
  dplyr::select(-c(cmep_date.T3, cmep_date.T4, cmep_total.T3, cmep_total.T4, ASQ_total.T3, ASQ_total.T4)) %>%
  distinct()

dups <-
  dem_plus_tan_ahc_merge6 %>%
  filter(duplicated(ELS_ID)) # no redundancies
```



## Merging with ELS data

```{r, message=FALSE}
# els 
els_sev_fp <- "~/Dropbox/JSK_SC/els_measures/els_severity_scores_includingTK20210204.csv"
els_sev <-
  read_csv(els_sev_fp) %>%
  mutate(ELS_ID = factor(ELS_ID)) %>%
  dplyr::select(ELS_ID, sumsev_type_t1)


dem_plus_tan_ahc_merge7 <-
  left_join(
    dem_plus_tan_ahc_merge6,
    els_sev,
    by = "ELS_ID"
    ) 
```


## removing those in early puberty - should i keep this range?

```{r}
table(dem_plus_tan_ahc_merge7$tanner_average_ahc)
earlytan <- c(2, 2.5, 2.5, 2.5)
earlytan_out <-  which(dem_plus_tan_ahc_merge7$tanner_average_ahc %in% c(earlytan))
earlytan_out
dem_plus_tan_ahc_merge7[earlytan_out, ]$ELS_ID
# 166 188 202 216 


dem_plus_tan_ahc_merge8 <-
  dem_plus_tan_ahc_merge7 %>%
  # filter(
  #   !ELS_ID == "166",
  #   !ELS_ID == "188",
  #   !ELS_ID == "202",
  #   !ELS_ID == "216"
  #   ) %>%
  dplyr::mutate(
    ELS_ID = factor(ELS_ID),
    sex = factor(sex),
    Household_Income_ahc =
      ifelse(Household_Income_ahc == "11", NA, Household_Income_ahc)
  )


dup <-
  dem_plus_tan_ahc_merge8 %>%
  filter(duplicated(ELS_ID))

ahc_summary_fp <- "~/Dropbox/JSK_SC/curating_data/3_actigraphy_ema_data_summary.csv"
ahc_summary_df <- read_csv(ahc_summary_fp) %>%
  dplyr::mutate(ELS_ID = factor(ELS_ID)) %>%
  dplyr::select(
    ELS_ID, race, gender_t3, gender_t4, 
  ) %>%
  dplyr::mutate(
    ELS_ID = factor(ELS_ID),
    race = factor(race),
    gender_t3 = factor(gender_t3),
    gender_t4 = factor(gender_t4)
  ) 

dem_plus_tan_ahc_merge9 <-
  left_join(
    dem_plus_tan_ahc_merge8,
    ahc_summary_df,
    by = "ELS_ID"
  ) %>%
  distinct()
```

### creating COVID variable

```{r}
covid_Date <- ymd("2020-03-17")
dem_plus_tan_ahc_merge10 <-
  dem_plus_tan_ahc_merge9 %>%
  dplyr::mutate(
    COVID = 
      ifelse(
        tanner_date_ahc > covid_Date,
        "yes",
        "no"
        ),
    COVID = factor(COVID)
    )
```



## Write df for next step

```{r}
dem_plus_tan_ahc_merged_fp <- "~/Dropbox/JSK_SC/_scripts/1_demo_wrangling/dem_plus_tan_ahc_merged.csv"
write_csv(dem_plus_tan_ahc_merge10, dem_plus_tan_ahc_merged_fp)
```

